# Generated by Django 4.1.7 on 2023-12-04 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_alter_ticket_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
